export const DEMO_STUDENT = {
  id: 'student-1', name: 'Arif Rahman', email: 'arif.rahman@premier.edu',
  department: 'CSE', batch: '2023', section: 'A', role: 'student' as const,
  bio: 'Computer Science student passionate about algorithms and distributed systems. Active in the Premier Tech Society.',
  skills: ['Python', 'Java', 'React', 'Data Structures', 'Machine Learning'],
  posts: 14, resources: 3, connections: 8,
};

export const DEMO_ALUMNI = {
  id: 'alumni-1', name: 'Tanvir Ahmed', email: 'tanvir.ahmed@orbitlabs.io',
  department: 'CSE', batch: '2019', graduationYear: '2023',
  company: 'Orbit Labs', jobTitle: 'Software Engineer', location: 'Dhaka, Bangladesh',
  role: 'alumni' as const,
  bio: 'Software Engineer at Orbit Labs specializing in backend systems and microservices architecture. Premier University CSE alumnus proud to give back.',
  skills: ['Go', 'Kubernetes', 'PostgreSQL', 'gRPC', 'System Design'],
  achievements: ['Dean\'s List 2022', 'Best Capstone Project Award'],
  careerTimeline: [
    { year: '2023–Present', role: 'Software Engineer', company: 'Orbit Labs' },
    { year: '2022–2023', role: 'Junior Developer', company: 'TechBase BD' },
  ],
};

export const DEMO_ADMIN = {
  id: 'admin-1', name: 'Dr. Admin', email: 'admin@premier.edu', role: 'admin' as const,
};

export const ALUMNI_LIST = [
  { id: 'a1', name: 'Tanvir Ahmed', department: 'CSE', batch: '2019', graduationYear: '2023', company: 'Orbit Labs', jobTitle: 'Software Engineer', location: 'Dhaka', bio: 'Backend systems engineer specializing in distributed architecture.', skills: ['Go', 'Kubernetes', 'PostgreSQL', 'Docker'], connected: false, careerTimeline: [{ year: '2023–Present', role: 'Software Engineer', company: 'Orbit Labs' }, { year: '2022', role: 'Junior Developer', company: 'TechBase BD' }] },
  { id: 'a2', name: 'Nusrat Jahan', department: 'CSE', batch: '2018', graduationYear: '2022', company: 'TechVentures', jobTitle: 'Product Manager', location: 'Singapore', bio: 'Product leader with expertise in fintech and mobile platforms.', skills: ['Product Strategy', 'Agile', 'User Research', 'Roadmapping'], connected: false, careerTimeline: [{ year: '2024–Present', role: 'Product Manager', company: 'TechVentures' }, { year: '2022', role: 'Associate PM', company: 'FinEdge' }] },
  { id: 'a3', name: 'Mahbub Alam', department: 'CSE', batch: '2020', graduationYear: '2024', company: 'DataCore', jobTitle: 'Full Stack Developer', location: 'Dhaka', bio: 'Full stack developer with React and Node.js expertise.', skills: ['React', 'Node.js', 'MongoDB', 'TypeScript'], connected: false, careerTimeline: [{ year: '2024–Present', role: 'Full Stack Developer', company: 'DataCore' }] },
  { id: 'a4', name: 'Fatima Khan', department: 'CSE', batch: '2019', graduationYear: '2023', company: 'Analytics Pro', jobTitle: 'Data Scientist', location: 'Dhaka', bio: 'Data scientist working on NLP and predictive modeling.', skills: ['Python', 'TensorFlow', 'Spark', 'R', 'SQL'], connected: false, careerTimeline: [{ year: '2023–Present', role: 'Data Scientist', company: 'Analytics Pro' }, { year: '2022', role: 'Data Analyst', company: 'InsightBD' }] },
  { id: 'a5', name: 'Rafi Islam', department: 'CSE', batch: '2017', graduationYear: '2021', company: 'CloudBase', jobTitle: 'DevOps Engineer', location: 'Dhaka', bio: 'DevOps engineer focused on CI/CD pipelines and cloud infrastructure.', skills: ['AWS', 'Terraform', 'Ansible', 'Jenkins', 'Linux'], connected: false, careerTimeline: [{ year: '2023–Present', role: 'Senior DevOps Engineer', company: 'CloudBase' }, { year: '2021', role: 'DevOps Engineer', company: 'CloudBase' }] },
  { id: 'a6', name: 'Sabrina Hossain', department: 'CSE', batch: '2021', graduationYear: '2025', company: 'Creative Studio', jobTitle: 'UI/UX Designer', location: 'Dhaka', bio: 'Designer creating elegant digital experiences for web and mobile.', skills: ['Figma', 'Adobe XD', 'Prototyping', 'Design Systems'], connected: false, careerTimeline: [{ year: '2025–Present', role: 'UI/UX Designer', company: 'Creative Studio' }] },
  { id: 'a7', name: 'Karim Hassan', department: 'CSE', batch: '2020', graduationYear: '2024', company: 'FinTech Solutions', jobTitle: 'Backend Developer', location: 'Dhaka', bio: 'Backend developer specializing in financial systems and APIs.', skills: ['Java', 'Spring Boot', 'PostgreSQL', 'RabbitMQ'], connected: false, careerTimeline: [{ year: '2024–Present', role: 'Backend Developer', company: 'FinTech Solutions' }] },
  { id: 'a8', name: 'Priya Sharma', department: 'CSE', batch: '2018', graduationYear: '2022', company: 'AI Ventures', jobTitle: 'ML Engineer', location: 'Bangalore, India', bio: 'Machine learning engineer working on computer vision applications.', skills: ['PyTorch', 'OpenCV', 'CUDA', 'MLflow', 'Python'], connected: false, careerTimeline: [{ year: '2023–Present', role: 'Senior ML Engineer', company: 'AI Ventures' }, { year: '2022', role: 'ML Engineer', company: 'AI Ventures' }] },
  { id: 'a9', name: 'Tariq Mahmud', department: 'CSE', batch: '2016', graduationYear: '2020', company: 'StartupHub', jobTitle: 'CTO', location: 'Dhaka', bio: 'Tech leader and co-founder driving innovation in the startup ecosystem.', skills: ['System Architecture', 'Leadership', 'Product Strategy', 'Fundraising'], connected: false, careerTimeline: [{ year: '2022–Present', role: 'CTO', company: 'StartupHub' }, { year: '2020', role: 'Lead Developer', company: 'TechBD' }] },
  { id: 'a10', name: 'Layla Rahman', department: 'CSE', batch: '2021', graduationYear: '2025', company: 'WebCraft', jobTitle: 'Frontend Developer', location: 'Dhaka', bio: 'Frontend developer crafting pixel-perfect web experiences with React.', skills: ['React', 'TypeScript', 'CSS', 'Next.js', 'Storybook'], connected: false, careerTimeline: [{ year: '2025–Present', role: 'Frontend Developer', company: 'WebCraft' }] },
  { id: 'a11', name: 'Omar Faruk', department: 'CSE', batch: '2017', graduationYear: '2021', company: 'Enterprise Tech', jobTitle: 'Systems Architect', location: 'Dhaka', bio: 'Enterprise architect designing large-scale distributed systems.', skills: ['Java', 'Kafka', 'Cassandra', 'Microservices', 'Design Patterns'], connected: false, careerTimeline: [{ year: '2024–Present', role: 'Systems Architect', company: 'Enterprise Tech' }, { year: '2021', role: 'Senior Developer', company: 'Enterprise Tech' }] },
  { id: 'a12', name: 'Aisha Begum', department: 'CSE', batch: '2022', graduationYear: '2026', company: 'TestPro', jobTitle: 'QA Engineer', location: 'Dhaka', bio: 'QA engineer ensuring software quality through automated testing.', skills: ['Selenium', 'Cypress', 'Jest', 'Postman', 'JIRA'], connected: false, careerTimeline: [{ year: '2026–Present', role: 'QA Engineer', company: 'TestPro' }] },
  { id: 'a13', name: 'Zahir Uddin', department: 'CSE', batch: '2019', graduationYear: '2023', company: 'CloudNine', jobTitle: 'Cloud Engineer', location: 'Dhaka', bio: 'Cloud engineer managing multi-cloud infrastructure and optimization.', skills: ['GCP', 'AWS', 'Terraform', 'Python', 'Prometheus'], connected: false, careerTimeline: [{ year: '2023–Present', role: 'Cloud Engineer', company: 'CloudNine' }] },
  { id: 'a14', name: 'Mitu Akter', department: 'CSE', batch: '2021', graduationYear: '2025', company: 'DesignHub', jobTitle: 'Product Designer', location: 'Dhaka', bio: 'Product designer focusing on user-centered mobile applications.', skills: ['Figma', 'SwiftUI', 'Prototyping', 'User Testing'], connected: false, careerTimeline: [{ year: '2025–Present', role: 'Product Designer', company: 'DesignHub' }] },
  { id: 'a15', name: 'Naeem Chowdhury', department: 'CSE', batch: '2018', graduationYear: '2022', company: 'SecureNet', jobTitle: 'Security Engineer', location: 'Dhaka', bio: 'Security engineer specializing in penetration testing and incident response.', skills: ['Penetration Testing', 'SIEM', 'Python', 'Network Security'], connected: false, careerTimeline: [{ year: '2023–Present', role: 'Security Engineer', company: 'SecureNet' }, { year: '2022', role: 'Security Analyst', company: 'SecureNet' }] },
];

export const RESOURCES = [
  { id: 'r1', title: 'Data Structures — Complete Lecture Notes', course: 'Data Structures', semester: '3rd', uploader: 'Arif Rahman', uploadDate: '2026-07-15', fileSize: '4.2 MB', fileType: 'PDF', description: 'Comprehensive lecture notes covering arrays, linked lists, trees, graphs, and hash tables with worked examples.', downloads: 142, comments: 8, commentList: [{ author: 'Nadia Islam', text: 'Super helpful, especially the tree diagrams!', date: '2026-07-17' }, { author: 'Siam Khan', text: 'Thanks for uploading this!', date: '2026-07-20' }] },
  { id: 'r2', title: 'Algorithms — Problem Set Solutions', course: 'Algorithms', semester: '4th', uploader: 'Priya Sharma (Alumni)', uploadDate: '2026-06-20', fileSize: '2.8 MB', fileType: 'PDF', description: 'Worked solutions for all algorithm problem sets with full complexity analysis.', downloads: 98, comments: 5, commentList: [{ author: 'Arif Rahman', text: 'Really clear explanations for the DP problems.', date: '2026-06-22' }] },
  { id: 'r3', title: 'DBMS — ER Diagram Collection', course: 'DBMS', semester: '3rd', uploader: 'Mahbub Alam (Alumni)', uploadDate: '2026-07-01', fileSize: '1.5 MB', fileType: 'PDF', description: 'Entity-Relationship diagrams for 25 real-world database design scenarios with normalization steps.', downloads: 201, comments: 12, commentList: [{ author: 'Tanvim Hossain', text: 'This is gold for exam prep!', date: '2026-07-03' }] },
  { id: 'r4', title: 'Operating Systems — Memory Management Notes', course: 'Operating Systems', semester: '5th', uploader: 'Tanvir Ahmed (Alumni)', uploadDate: '2026-05-12', fileSize: '3.1 MB', fileType: 'PDF', description: 'Detailed notes on virtual memory, paging, segmentation, and page replacement algorithms.', downloads: 167, comments: 9, commentList: [{ author: 'Reshma Begum', text: 'Finally understood page replacement!', date: '2026-05-14' }] },
  { id: 'r5', title: 'Computer Networks — Protocol Reference', course: 'Computer Networks', semester: '5th', uploader: 'Omar Faruk (Alumni)', uploadDate: '2026-04-28', fileSize: '5.7 MB', fileType: 'PDF', description: 'Quick reference guide for TCP/IP, HTTP, DNS, and network protocols with diagrams.', downloads: 189, comments: 14, commentList: [{ author: 'Jahid Hassan', text: 'The OSI model comparison table is excellent.', date: '2026-04-30' }] },
  { id: 'r6', title: 'Data Structures — Assignment 3 Solutions', course: 'Data Structures', semester: '3rd', uploader: 'Arif Rahman', uploadDate: '2026-08-01', fileSize: '0.8 MB', fileType: 'PDF', description: 'Complete solutions for Assignment 3 covering heap operations and graph traversal.', downloads: 55, comments: 3, commentList: [] },
  { id: 'r7', title: 'Algorithms — Dynamic Programming Cheat Sheet', course: 'Algorithms', semester: '4th', uploader: 'Fatima Khan (Alumni)', uploadDate: '2026-07-22', fileSize: '0.5 MB', fileType: 'PDF', description: 'Condensed reference for DP patterns and common problems. Must-have for exams.', downloads: 310, comments: 22, commentList: [{ author: 'Arif Rahman', text: 'Saved me so much time!', date: '2026-07-25' }] },
  { id: 'r8', title: 'DBMS — Lab Manual Semester 3', course: 'DBMS', semester: '3rd', uploader: 'Rafi Islam (Alumni)', uploadDate: '2026-06-08', fileSize: '2.2 MB', fileType: 'PDF', description: 'Complete lab manual with SQL exercises and solutions for all DBMS labs.', downloads: 278, comments: 16, commentList: [] },
];

export const EVENTS = [
  { id: 'ev1', title: 'Career Fair 2026', category: 'Career', date: '2026-09-15', time: '10:00 AM – 4:00 PM', location: 'Premier University Main Auditorium', description: 'Annual career fair bringing together 30+ companies from tech, finance, and consulting. Dress professionally and bring your CV. Over 50 open positions expected.', organizer: 'Career Development Office', attendees: 342, rsvped: false, status: 'upcoming' },
  { id: 'ev2', title: 'AI & Machine Learning Workshop', category: 'Academic', date: '2026-09-05', time: '2:00 PM – 5:00 PM', location: 'CSE Building, Room 301', description: 'Hands-on workshop on practical machine learning with PyTorch. Beginner-friendly with experienced alumni mentors guiding each session.', organizer: 'CSE Student Association', attendees: 89, rsvped: false, status: 'upcoming' },
  { id: 'ev3', title: 'Alumni Networking Night', category: 'Networking', date: '2026-09-20', time: '6:00 PM – 9:00 PM', location: 'Premier University Faculty Lounge', description: 'Evening networking event connecting students with alumni working across the tech industry. Light refreshments included. Open to all students.', organizer: 'Alumni Relations Office', attendees: 156, rsvped: false, status: 'upcoming' },
  { id: 'ev4', title: 'HackPremier 2026', category: 'Community', date: '2026-10-01', time: '9:00 AM (48-hour event)', location: 'Premier University Innovation Lab', description: '48-hour hackathon with prizes up to BDT 1,00,000. Teams of 2–4 members. Build something that solves a real problem for the university community.', organizer: 'Premier Tech Society', attendees: 210, rsvped: false, status: 'upcoming' },
  { id: 'ev5', title: 'DBMS Guest Lecture — Industry Practices', category: 'Academic', date: '2026-08-28', time: '11:00 AM – 12:30 PM', location: 'CSE Building, Room 101', description: 'Industry expert from DataCore shares practical database design patterns used in production systems serving millions of users.', organizer: 'CSE Department', attendees: 67, rsvped: true, status: 'upcoming' },
  { id: 'ev6', title: 'Spring Programming Contest 2026', category: 'Academic', date: '2026-04-15', time: '10:00 AM – 2:00 PM', location: 'CSE Lab Complex', description: 'Competitive programming contest with algorithmic challenges across three difficulty levels. Individual participation.', organizer: 'CSE Student Association', attendees: 134, rsvped: true, status: 'past' },
  { id: 'ev7', title: 'Industry Seminar — Cloud Computing', category: 'Career', date: '2026-03-10', time: '3:00 PM – 5:00 PM', location: 'Online (Zoom)', description: 'Cloud architects from leading companies shared insights on modern cloud architecture and career opportunities in the cloud industry.', organizer: 'Career Development Office', attendees: 298, rsvped: true, status: 'past' },
];

export const JOBS = [
  { id: 'j1', title: 'Software Engineer', company: 'TechVentures BD', type: 'Full-time', location: 'Dhaka, Bangladesh', deadline: '2026-09-30', description: 'Join our growing engineering team to build scalable web applications serving millions of users across Bangladesh.', requirements: ['3+ years React experience', 'Strong JavaScript/TypeScript', 'REST API design', 'Git proficiency'], eligibility: 'CSE graduates, Batch 2022 or earlier', postedBy: 'Nusrat Jahan (Alumni)', postedByRole: 'Product Manager, TechVentures', postedDate: '2026-08-15', applied: false, approved: true, salary: '60,000–90,000 BDT/month' },
  { id: 'j2', title: 'Data Analyst Intern', company: 'Analytics Hub', type: 'Internship', location: 'Dhaka, Bangladesh', deadline: '2026-09-15', description: 'Work with our data team on real-world analytics projects. Learn industry tools and best practices from senior data scientists.', requirements: ['Python or R skills', 'SQL proficiency', 'Tableau or Power BI knowledge', '3rd or 4th year student'], eligibility: 'CSE, EEE, or Statistics students', postedBy: 'Fatima Khan (Alumni)', postedByRole: 'Data Scientist, Analytics Pro', postedDate: '2026-08-10', applied: false, approved: true, salary: '20,000 BDT/month stipend' },
  { id: 'j3', title: 'Frontend Developer', company: 'WebCraft Agency', type: 'Full-time', location: 'Dhaka, Bangladesh', deadline: '2026-10-05', description: 'Create beautiful, responsive web interfaces for our diverse client portfolio using React and modern CSS frameworks.', requirements: ['React and Next.js', 'CSS/Tailwind CSS', 'Strong UI/UX sensibility', 'Portfolio required'], eligibility: 'CSE graduates, any batch', postedBy: 'Layla Rahman (Alumni)', postedByRole: 'Frontend Developer, WebCraft', postedDate: '2026-08-20', applied: false, approved: true, salary: '45,000–70,000 BDT/month' },
  { id: 'j4', title: 'ML Research Intern', company: 'AI Research Labs', type: 'Internship', location: 'Remote', deadline: '2026-09-20', description: 'Research internship focused on natural language processing and large language model fine-tuning for Bengali language tasks.', requirements: ['Strong Python skills', 'PyTorch or TensorFlow', 'Published research a plus', 'Strong mathematics background'], eligibility: '4th year or graduate CSE students', postedBy: 'Priya Sharma (Alumni)', postedByRole: 'ML Engineer, AI Ventures', postedDate: '2026-08-05', applied: false, approved: true, salary: '25,000 BDT/month stipend' },
  { id: 'j5', title: 'Backend Developer', company: 'CloudBase Systems', type: 'Full-time', location: 'Dhaka, Bangladesh', deadline: '2026-10-10', description: 'Design and build high-performance backend services handling 10M+ daily requests with strict latency requirements.', requirements: ['Go or Java', 'PostgreSQL and Redis', 'Docker/Kubernetes', 'System design skills'], eligibility: 'CSE graduates with 1+ year experience', postedBy: 'Rafi Islam (Alumni)', postedByRole: 'DevOps Engineer, CloudBase', postedDate: '2026-08-18', applied: false, approved: true, salary: '70,000–1,00,000 BDT/month' },
  { id: 'j6', title: 'Product Manager', company: 'Orbit Labs', type: 'Full-time', location: 'Dhaka, Bangladesh', deadline: '2026-09-25', description: 'Lead product development for our B2B SaaS platform. Work closely with engineering and design teams to ship impactful features.', requirements: ['2+ years PM experience', 'Agile/Scrum methodology', 'Data-driven decision making', 'Strong communication skills'], eligibility: 'CSE or Business graduates', postedBy: 'Tanvir Ahmed (Alumni)', postedByRole: 'Software Engineer, Orbit Labs', postedDate: '2026-08-12', applied: false, approved: true, salary: '80,000–1,20,000 BDT/month' },
  { id: 'j7', title: 'DevOps Engineer', company: 'DataCore Technologies', type: 'Full-time', location: 'Dhaka, Bangladesh', deadline: '2026-10-15', description: 'Manage cloud infrastructure, CI/CD pipelines, and ensure 99.9% uptime for production systems serving enterprise clients.', requirements: ['AWS or GCP certification preferred', 'Terraform and Ansible', 'Jenkins or GitHub Actions', 'Linux administration'], eligibility: 'CSE graduates, any batch', postedBy: 'Mahbub Alam (Alumni)', postedByRole: 'Full Stack Developer, DataCore', postedDate: '2026-08-22', applied: false, approved: true, salary: '65,000–95,000 BDT/month' },
  { id: 'j8', title: 'Security Analyst', company: 'SecureNet BD', type: 'Full-time', location: 'Dhaka, Bangladesh', deadline: '2026-09-28', description: 'Protect our organization from cyber threats through monitoring, analysis, incident response, and security awareness programs.', requirements: ['Security certifications a plus', 'SIEM tool experience', 'Network security knowledge', 'Python scripting'], eligibility: 'CSE graduates with interest in cybersecurity', postedBy: 'Naeem Chowdhury (Alumni)', postedByRole: 'Security Engineer, SecureNet', postedDate: '2026-08-08', applied: false, approved: true, salary: '55,000–80,000 BDT/month' },
  { id: 'j9', title: 'UI/UX Design Intern', company: 'Creative Studio BD', type: 'Internship', location: 'Dhaka, Bangladesh', deadline: '2026-09-10', description: 'Join our design team to create stunning interfaces for mobile and web applications for our growing list of startup clients.', requirements: ['Figma proficiency required', 'Portfolio mandatory', 'Understanding of UX principles', '2nd year or above'], eligibility: 'CSE students with design interest', postedBy: 'Sabrina Hossain (Alumni)', postedByRole: 'UI/UX Designer, Creative Studio', postedDate: '2026-08-01', applied: false, approved: true, salary: '15,000 BDT/month stipend' },
  { id: 'j10', title: 'Full Stack Developer', company: 'FinTech Solutions BD', type: 'Full-time', location: 'Dhaka, Bangladesh', deadline: '2026-10-20', description: 'Build comprehensive financial technology solutions using modern web technologies for Bangladesh\'s growing fintech sector.', requirements: ['React + Node.js or Spring Boot', 'Financial domain knowledge a plus', 'SQL databases', 'RESTful API integration'], eligibility: 'CSE graduates, Batch 2021 or earlier', postedBy: 'Karim Hassan (Alumni)', postedByRole: 'Backend Developer, FinTech Solutions', postedDate: '2026-08-25', applied: false, approved: false, salary: '55,000–85,000 BDT/month' },
];

export const ANNOUNCEMENTS = [
  { id: 'ann1', title: 'Final Examination Schedule — Fall 2026', category: 'Academic', content: 'The final examination schedule for Fall 2026 semester has been published. Examinations begin October 15, 2026. Please review the schedule carefully on the registrar portal and report any conflicts within 5 working days. All make-up exam requests must be submitted by October 10.', date: '2026-08-27', author: 'Academic Affairs Office', priority: 'high', target: 'All Students' },
  { id: 'ann2', title: 'Campus Network Maintenance — September 3', category: 'General', content: 'Scheduled maintenance of the campus network infrastructure will be conducted on September 3, 2026 from 12:00 AM to 6:00 AM. All network services including Wi-Fi and intranet will be unavailable during this window. Please plan accordingly.', date: '2026-08-25', author: 'IT Department', priority: 'medium', target: 'Everyone' },
  { id: 'ann3', title: 'Alumni Meet 2026 — Registration Now Open', category: 'Event', content: 'Registration for the Premier University Alumni Meet 2026 is now open. The event will be held on October 25, 2026 at the Premier University campus. Alumni and current students are both welcome. Early registration discount available until September 15.', date: '2026-08-23', author: 'Alumni Relations Office', priority: 'medium', target: 'Alumni & Students' },
  { id: 'ann4', title: 'CSE Department Lab Hours Extended', category: 'Department', content: 'Effective September 1, 2026, the CSE computer labs (Lab 201, 202, 203) will be open until 10:00 PM on weekdays. Weekend hours remain unchanged (9 AM – 6 PM). Please carry your valid student ID for after-hours access.', date: '2026-08-20', author: 'CSE Department', priority: 'low', target: 'CSE Students' },
  { id: 'ann5', title: 'Merit Scholarship Applications Open — Fall 2026', category: 'Academic', content: 'Applications for the Premier University Merit Scholarship for Fall 2026 are now open. Students with CGPA 3.5+ are eligible. Submit applications through the student portal by September 30, 2026. Financial aid and need-based components are also available.', date: '2026-08-18', author: 'Financial Aid Office', priority: 'high', target: 'All Students' },
  { id: 'ann6', title: 'Library East Wing Renovation — Phase 2', category: 'General', content: 'Phase 2 of the library east wing renovation begins September 10, 2026. The east reading room will be temporarily closed. Alternative study spaces are available in the Student Center and Faculty Lounge. Expected completion: December 2026.', date: '2026-08-15', author: 'Facilities Management', priority: 'low', target: 'Everyone' },
  { id: 'ann7', title: 'New Elective: Deep Learning Applications (CSE 4701)', category: 'Academic', content: 'A new elective course "Deep Learning Applications" (CSE 4701) will be offered from Fall 2026. The course covers CNNs, RNNs, Transformers, and real-world applications. Limited to 40 students. Register through the course portal before September 5.', date: '2026-08-12', author: 'CSE Department', priority: 'medium', target: 'CSE Students' },
];

export const COMMUNITY_POSTS = [
  { id: 'cp1', author: 'Arif Rahman', authorRole: 'Student · CSE 2023 A', type: 'Discussion', content: 'Anyone forming a study group for the upcoming Data Structures final? Looking for 3–4 people to study together this weekend. Planning to cover trees, graphs, and dynamic programming. DM me or comment below!', date: '2026-08-28', upvotes: 12, comments: 3, upvoted: false, reported: false, commentList: [{ id: 'c1', author: 'Rima Akter', text: 'I am in! Let me know the time and place.', date: '2026-08-28' }, { id: 'c2', author: 'Siam Khan', text: 'Count me in too. Struggling with graph traversal specifically.', date: '2026-08-28' }, { id: 'c3', author: 'Mehedi Hasan', text: 'Would love to join. Can we meet in the CSE lab?', date: '2026-08-28' }] },
  { id: 'cp2', author: 'Nadia Islam', authorRole: 'Student · CSE 2023 A', type: 'Resource', content: 'Sharing my DBMS lab notes for this week! Covers SQL joins, subqueries, and stored procedures with examples from our lab exercises. Hope it helps. Please upvote if useful so more people see it!', date: '2026-08-27', upvotes: 28, comments: 2, upvoted: false, reported: false, commentList: [{ id: 'c4', author: 'Arif Rahman', text: 'Thank you so much! These are really clear.', date: '2026-08-27' }, { id: 'c5', author: 'Priya Das', text: 'This helped me understand stored procedures finally!', date: '2026-08-28' }] },
  { id: 'cp3', author: 'Tanvim Hossain', authorRole: 'Student · CSE 2023 A', type: 'Question', content: 'Can someone explain the difference between a process and a thread in simple terms? The lecture slides are confusing. Specifically unclear on how memory is shared between threads vs processes. Any help appreciated!', date: '2026-08-26', upvotes: 8, comments: 2, upvoted: false, reported: false, commentList: [{ id: 'c6', author: 'Arif Rahman', text: 'Processes have separate memory spaces; threads share memory within the same process. Think of a process as a house and threads as rooms in that house.', date: '2026-08-26' }, { id: 'c7', author: 'Tanvim Hossain', text: 'That analogy helps so much, thank you!', date: '2026-08-26' }] },
  { id: 'cp4', author: 'Reshma Begum', authorRole: 'Student · CSE 2023 A', type: 'Discussion', content: 'Did everyone register for the Career Fair on September 15? Heard TechVentures and Orbit Labs will be there — great chance for internship applications! Let\'s go as a batch group. Who is interested?', date: '2026-08-25', upvotes: 34, comments: 1, upvoted: false, reported: false, commentList: [{ id: 'c8', author: 'Arif Rahman', text: 'Already registered! Definitely going as a group.', date: '2026-08-25' }] },
  { id: 'cp5', author: 'Jahid Hassan', authorRole: 'Student · CSE 2023 A', type: 'Question', content: 'Is anyone else finding Algorithms Assignment 4 really hard? The dynamic programming problem on sequence alignment is giving me trouble. Any hints without spoiling the full answer?', date: '2026-08-24', upvotes: 15, comments: 2, upvoted: false, reported: false, commentList: [{ id: 'c9', author: 'Nadia Islam', text: 'Try drawing the DP table first — it makes the recurrence pattern much clearer.', date: '2026-08-24' }, { id: 'c10', author: 'Arif Rahman', text: 'The key insight: track edit distance. Think about what happens when characters match vs do not match.', date: '2026-08-24' }] },
];

export const ALUMNI_COMMUNITY_POSTS = [
  { id: 'ap1', author: 'Tariq Mahmud', authorRole: 'Alumni · CSE 2016 · CTO, StartupHub', type: 'Discussion', content: 'To all Premier University alumni in the startup space: we are hosting a casual meetup next Friday in Dhaka. Come share what you are building and meet fellow founders from our batch. DM for location details.', date: '2026-08-27', upvotes: 41, comments: 8, upvoted: false, reported: false, commentList: [{ id: 'ap1c1', author: 'Nusrat Jahan', text: 'Would love to join! Count me in.', date: '2026-08-27' }] },
  { id: 'ap2', author: 'Nusrat Jahan', authorRole: 'Alumni · CSE 2018 · Product Manager, TechVentures', type: 'Resource', content: 'Sharing the product roadmap template I use at TechVentures. It has been very useful for aligning engineering and business stakeholders. Free to use — just give attribution if you share publicly.', date: '2026-08-26', upvotes: 67, comments: 12, upvoted: false, reported: false, commentList: [{ id: 'ap2c1', author: 'Fatima Khan', text: 'This is brilliant, thank you Nusrat!', date: '2026-08-26' }] },
  { id: 'ap3', author: 'Priya Sharma', authorRole: 'Alumni · CSE 2018 · ML Engineer, AI Ventures', type: 'Discussion', content: 'Excited to share that our paper on Bengali NLP was accepted at ACL 2027! Happy to mentor any current students interested in NLP research. Reach out if you want to discuss research directions.', date: '2026-08-25', upvotes: 89, comments: 15, upvoted: false, reported: false, commentList: [{ id: 'ap3c1', author: 'Tanvir Ahmed', text: 'Congratulations! Well deserved.', date: '2026-08-25' }] },
];

export const NOTIFICATIONS = [
  { id: 'n1', type: 'comment', message: 'Nadia Islam commented on your post "Study group for Data Structures"', time: '10 minutes ago', read: false, link: 'community' },
  { id: 'n2', type: 'resource', message: 'New resource in CSE Batch 2023 A: "Algorithms — Dynamic Programming Cheat Sheet"', time: '2 hours ago', read: false, link: 'resources' },
  { id: 'n3', type: 'event', message: 'Reminder: "AI & Machine Learning Workshop" is in 2 days — September 5', time: '3 hours ago', read: false, link: 'events' },
  { id: 'n4', type: 'announcement', message: 'New announcement: "Final Examination Schedule — Fall 2026"', time: '5 hours ago', read: false, link: 'announcements' },
  { id: 'n5', type: 'job', message: 'New internship posted by Fatima Khan: "Data Analyst Intern at Analytics Hub"', time: '1 day ago', read: true, link: 'jobs' },
  { id: 'n6', type: 'connection', message: 'Layla Rahman (Alumni) accepted your connection request', time: '2 days ago', read: true, link: 'alumni-directory' },
  { id: 'n7', type: 'comment', message: 'Tanvim Hossain replied to your comment in the community discussion', time: '2 days ago', read: true, link: 'community' },
  { id: 'n8', type: 'event', message: 'RSVP confirmed: "DBMS Guest Lecture — Industry Practices" on August 28', time: '3 days ago', read: true, link: 'events' },
];

export const COMMUNITY_MEMBERS = [
  { id: 'cm1', name: 'Arif Rahman', batch: '2023', section: 'A', online: true },
  { id: 'cm2', name: 'Nadia Islam', batch: '2023', section: 'A', online: true },
  { id: 'cm3', name: 'Tanvim Hossain', batch: '2023', section: 'A', online: false },
  { id: 'cm4', name: 'Reshma Begum', batch: '2023', section: 'A', online: true },
  { id: 'cm5', name: 'Jahid Hassan', batch: '2023', section: 'A', online: false },
  { id: 'cm6', name: 'Rima Akter', batch: '2023', section: 'A', online: false },
  { id: 'cm7', name: 'Siam Khan', batch: '2023', section: 'A', online: true },
  { id: 'cm8', name: 'Priya Das', batch: '2023', section: 'A', online: false },
  { id: 'cm9', name: 'Mehedi Hasan', batch: '2023', section: 'A', online: false },
  { id: 'cm10', name: 'Farhan Uddin', batch: '2023', section: 'A', online: true },
  { id: 'cm11', name: 'Khadija Sultana', batch: '2023', section: 'A', online: false },
  { id: 'cm12', name: 'Jubayer Hossain', batch: '2023', section: 'A', online: true },
];

export const ADMIN_STATS = {
  totalStudents: 5247, totalAlumni: 1284, activeCommunities: 52,
  postsToday: 147, pendingReports: 8, upcomingEvents: 5,
};

export const ACTIVITY_DATA = [
  { day: 'Mon', posts: 89, logins: 312 },
  { day: 'Tue', posts: 112, logins: 398 },
  { day: 'Wed', posts: 98, logins: 356 },
  { day: 'Thu', posts: 134, logins: 421 },
  { day: 'Fri', posts: 147, logins: 489 },
  { day: 'Sat', posts: 72, logins: 198 },
  { day: 'Sun', posts: 56, logins: 143 },
];

export const ADMIN_USERS = [
  { id: 'u1', name: 'Arif Rahman', role: 'Student', department: 'CSE', batch: '2023', status: 'active', email: 'arif@premier.edu', joinDate: '2023-09-01', posts: 14, reports: 0 },
  { id: 'u2', name: 'Nadia Islam', role: 'Student', department: 'CSE', batch: '2023', status: 'active', email: 'nadia@premier.edu', joinDate: '2023-09-01', posts: 22, reports: 0 },
  { id: 'u3', name: 'Tanvir Ahmed', role: 'Alumni', department: 'CSE', batch: '2019', status: 'active', email: 'tanvir@orbitlabs.io', joinDate: '2024-01-15', posts: 8, reports: 0 },
  { id: 'u4', name: 'Fatima Khan', role: 'Alumni', department: 'CSE', batch: '2019', status: 'active', email: 'fatima@analyticspro.com', joinDate: '2024-02-10', posts: 11, reports: 0 },
  { id: 'u5', name: 'Jahid Hassan', role: 'Student', department: 'CSE', batch: '2023', status: 'active', email: 'jahid@premier.edu', joinDate: '2023-09-01', posts: 6, reports: 1 },
  { id: 'u6', name: 'Reshma Begum', role: 'Student', department: 'EEE', batch: '2023', status: 'active', email: 'reshma@premier.edu', joinDate: '2023-09-01', posts: 18, reports: 0 },
  { id: 'u7', name: 'Rafi Islam', role: 'Alumni', department: 'CSE', batch: '2017', status: 'active', email: 'rafi@cloudbase.com', joinDate: '2024-03-05', posts: 5, reports: 0 },
  { id: 'u8', name: 'Tanvim Hossain', role: 'Student', department: 'CSE', batch: '2023', status: 'suspended', email: 'tanvim@premier.edu', joinDate: '2023-09-01', posts: 3, reports: 2 },
  { id: 'u9', name: 'Priya Sharma', role: 'Alumni', department: 'CSE', batch: '2018', status: 'active', email: 'priya@aiventures.com', joinDate: '2024-01-20', posts: 9, reports: 0 },
  { id: 'u10', name: 'Omar Faruk', role: 'Alumni', department: 'CSE', batch: '2017', status: 'pending', email: 'omar@enterprisetech.com', joinDate: '2026-08-25', posts: 0, reports: 0 },
  { id: 'u11', name: 'Sabrina Hossain', role: 'Alumni', department: 'CSE', batch: '2021', status: 'active', email: 'sabrina@creativestudio.com', joinDate: '2025-06-12', posts: 7, reports: 0 },
  { id: 'u12', name: 'Layla Rahman', role: 'Alumni', department: 'CSE', batch: '2021', status: 'active', email: 'layla@webcraft.com', joinDate: '2025-07-01', posts: 4, reports: 0 },
];

export const ADMIN_COMMUNITIES = [
  { id: 'com1', name: 'CSE Batch 2023 — Section A', type: 'Batch', members: 45, posts: 312, moderator: 'Nadia Islam', status: 'active' },
  { id: 'com2', name: 'CSE Batch 2023 — Section B', type: 'Batch', members: 43, posts: 287, moderator: 'Siam Khan', status: 'active' },
  { id: 'com3', name: 'CSE Batch 2022 — Section A', type: 'Batch', members: 48, posts: 598, moderator: 'Farhan Ahmed', status: 'active' },
  { id: 'com4', name: 'Premier University Alumni Network', type: 'Alumni', members: 1284, posts: 2145, moderator: 'Tariq Mahmud', status: 'active' },
  { id: 'com5', name: 'Data Structures & Algorithms Club', type: 'Academic', members: 342, posts: 812, moderator: 'Dr. Rahman', status: 'active' },
  { id: 'com6', name: 'Career & Internships Hub', type: 'Career', members: 567, posts: 234, moderator: 'Nusrat Jahan', status: 'active' },
  { id: 'com7', name: 'Premier Tech Society', type: 'Club', members: 189, posts: 445, moderator: 'Arif Rahman', status: 'active' },
  { id: 'com8', name: 'EEE Batch 2023', type: 'Batch', members: 41, posts: 198, moderator: null, status: 'needs_moderator' },
];

export const ADMIN_REPORTS = [
  { id: 'rep1', type: 'Post', content: 'Sharing external link for pirated textbooks', reporter: 'Nadia Islam', reported: 'Unknown User', reason: 'Spam', date: '2026-08-28', status: 'pending' },
  { id: 'rep2', type: 'Comment', content: 'Offensive language in community discussion', reporter: 'Reshma Begum', reported: 'Tanvim Hossain', reason: 'Inappropriate', date: '2026-08-27', status: 'pending' },
  { id: 'rep3', type: 'Resource', content: 'Uploaded exam answers — possible academic dishonesty', reporter: 'Dr. Rahman', reported: 'Jahid Hassan', reason: 'Other', date: '2026-08-26', status: 'pending' },
  { id: 'rep4', type: 'Post', content: 'Unrelated promotional content', reporter: 'Arif Rahman', reported: 'Unknown User', reason: 'Spam', date: '2026-08-25', status: 'resolved' },
  { id: 'rep5', type: 'Comment', content: 'Harassment in comment section', reporter: 'Khadija Sultana', reported: 'Unknown User', reason: 'Harassment', date: '2026-08-24', status: 'resolved' },
  { id: 'rep6', type: 'Job', content: 'Suspicious job posting — possibly fraudulent', reporter: 'Siam Khan', reported: 'Unknown User', reason: 'Spam', date: '2026-08-23', status: 'resolved' },
];

export const MODERATION_QUEUE = [
  { id: 'mq1', type: 'Post', author: 'New User 142', content: 'Selling digital notes at a discounted price — message me on WhatsApp at +880...', community: 'CSE Batch 2023 A', date: '2026-08-28', flagged: true },
  { id: 'mq2', type: 'Comment', author: 'Unknown Alumni', content: 'This is completely wrong information. You should not trust anything posted here...', community: 'Alumni Network', date: '2026-08-27', flagged: true },
  { id: 'mq3', type: 'Resource', author: 'Jahid Hassan', content: 'CSE 3105 Final Exam 2025 — Questions and Answers (Leaked)', community: 'Data Structures Club', date: '2026-08-26', flagged: true },
  { id: 'mq4', type: 'Post', author: 'Reshma Begum', content: 'Great study session yesterday! We covered all the important topics for the upcoming quiz.', community: 'CSE Batch 2023 A', date: '2026-08-28', flagged: false },
  { id: 'mq5', type: 'Post', author: 'Siam Khan', content: 'Anyone want to collaborate on the semester project? Looking for 2 people with frontend experience.', community: 'Career & Internships Hub', date: '2026-08-27', flagged: false },
];
